### ISSUE TITLE
Activity Feed needs styling

### ISSUE THREAD

**Issue by rodrigojv** [FundacionParaguaya/fp-psp-frontend#185]
The activity Feed needs to be styled with CSS in order to make it similar to the overall design of the site.

How it looks now:
![screen shot 2018-06-01 at 9 28 19 am](https://user-images.githubusercontent.com/17142306/40843216-41ec78fe-657e-11e8-80ef-59f30078f696.png)

It should look more like the screen-shot in #87 , without the 'under construction' background of course 😉

**Comment by Komorebi-Girl** [comment]
Hi @rodrigojv, I think I can write the css for the activity feed. I've tried looking through the code but I can't pinpoint where it is so I can apply the styling. Could you please let me know where I can find it?

**Comment by rodrigojv** [comment]
Thank you @gabrielci , I left a review on your PR.

**Comment by rodrigojv** [comment]
Hi @Komorebi-Girl , thank you so much for being interested in contributing to this project 😄 . 

We already have a PR for this issue, #196 and we're in the process of reviewing it and merging it to our development branch. 

I'm sorry it was not easy to find the activity feed, maybe we can improve the structure of the source code and also the description of the issue. Any suggestions are welcome :).

We may have some new first-timers-only issues in the future, and we will be glad to have your contribution in those when the time comes.

Thank you again 👍

**Comment by rodrigojv** [comment]
Closed by #196
