### ISSUE TITLE
We need a "Load More" button on all pages that have Card lists

### ISSUE THREAD

**Issue by rodrigojv** [FundacionParaguaya/fp-psp-frontend#187]
When you search or list families, organizations or users, you can see 12 cards. More cards are loaded when the user scrolls down. 

But this behaviour is not clear,  so we think we need a "Load More" button below the Card list, so that the user knows that are more items that are not displayed and he can load those items by clicking on the button.

This button will replace the scrolling behaviour. Or maybe not. 🤔

The alternative solution is, instead of the button, modifying the CSS so that there is always a scroll on the cards container, so that the user always knows that he or she can scroll.

**Comment by oskred** [comment]
Hello - if this issue is still open I'd like to give it a shot as my first PR. thanks

**Comment by DennisOnder** [comment]
Is the issue still open?

**Comment by rodrigojv** [comment]
It is still open, please go ahead @oskred.

**Comment by pA1nD** [comment]
@oskred This is no longer needed as we change the cards! #wontfix
