### ISSUE TITLE
Update Organization Edit: Add Multiselect for (Sub-) Organizations

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/fp-psp-frontend#243]
Mockup
https://2pz31h.axshare.com/#g=1&p=organization_edit

**Comment by diegotorrespy** [comment]
According to the mock up, the endpoint using to update organizations data will expect the next json format:

**PUT https://testing.backend.povertystoplight.org/api/v1/organizations/11**

`{
	"id":11,
	"name":"Spring - Study Programme",
	"code":"springsp",
	"description":"Spring - Study Programme",
	"isActive":"TRUE",
	"subOrganizations":[ 
		{"id":12}, 
		{"id":13}, 
		{"id":14} 
	]
}`

In the server, the subOrganizations param will be related to the organization that is updated in the moment. It is not a mandatory param so the json body could be like this:

`{
	"id":11,
	"name":"Spring - Study Programme",
	"code":"springsp",
	"description":"Spring - Study Programme",
	"isActive":"TRUE"
}`

If the organization has sub-organization's, this request will delete these.

**Comment by diegotorrespy** [comment]
The branch created for this feature is: _dtorres-groups-organizations-feature_

**Comment by Danman7** [comment]
Front-end branch is *multiproject-front-end*. I have implemented the multi-select which gets the organizations and adds them as described to the model for the PUT API call.

@diegotorrespy I update the organization, but when I make a GET request to get the updated organization, I can't see the subOrganizations anywhere in the response. Can you help me out?
