### ISSUE TITLE
Status/Purpose Documentation

### ISSUE THREAD

**Issue by bhylak** [FundacionParaguaya/fp-psp-frontend#9]
What's the status of this front end? Purpose and pictures would be helpful here.

**Comment by rodrigojv** [comment]
Hi @bhylak , the status as of right now is as follows:
1. Organization CRUD
2. Filling out surveys and see snapshots
3. Adding new survey using JSON

The purpose for the frontend is to match the mockups we have shared with you in a Google Docs, as far as layout and styles are concerned. And also provide the funcionality required for each of the mockups.

Here are some screen-shots of what we have as of today:
<img width="1401" alt="screen shot 2017-11-27 at 10 58 09 am" src="https://user-images.githubusercontent.com/17142306/33270226-0f195e3c-d362-11e7-9177-2f646729a93b.png">
<img width="1408" alt="screen shot 2017-11-27 at 10 56 20 am" src="https://user-images.githubusercontent.com/17142306/33270229-1505cd30-d362-11e7-8b72-be51b2082f48.png">
<img width="1397" alt="screen shot 2017-11-27 at 10 56 51 am" src="https://user-images.githubusercontent.com/17142306/33270234-1a858728-d362-11e7-9b94-4059c418a6d1.png">
<img width="1338" alt="screen shot 2017-11-27 at 10 58 22 am" src="https://user-images.githubusercontent.com/17142306/33270237-1df2948c-d362-11e7-83e7-4747c82a47e6.png">
<img width="1270" alt="screen shot 2017-11-27 at 10 58 46 am" src="https://user-images.githubusercontent.com/17142306/33270246-25c72b96-d362-11e7-8639-13929947897d.png">
<img width="1401" alt="screen shot 2017-11-27 at 10 57 22 am" src="https://user-images.githubusercontent.com/17142306/33270251-2c151378-d362-11e7-9372-3b9257636f65.png">

**Comment by rodrigojv** [comment]
We're also working on:
1. matching the styles of the mockups
2. being able to fill out surveys by selecting images
3. Adding families and other CRUDS

Yo can see here all the PR's i have yet to review and merge:
https://github.com/FundacionParaguaya/fp-psp-frontend/pulls

Please let me know @bhylak if that is useful.
